"use client";

import { ArrowLeft, Activity, Calculator, Calendar, Clock3, ReceiptText, Scale } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Badge, PageHeader, PageState } from "@/components/page-state";
import { useApi } from "@/lib/use-api";
import type { AccountPriority } from "@/types/dss";

type Detail = { account_key: string; account: string; priority: AccountPriority | null; rfm: Record<string, number> | null;
  settlement: Record<string, number> | null; critic_weights: Record<string, number>; sensitivity: Record<string, number | null>;
  transactions: Array<Record<string, string | number | boolean | null>> };
export default function AccountDetailsPage() {
  const key = decodeURIComponent(String(useParams().accountKey)); const { data, error, loading, reload } = useApi<Detail>(`/accounts/${encodeURIComponent(key)}`);
  const p = data?.priority;
  return <div className="page-stack"><Link className="back-link" href="/accounts"><ArrowLeft size={16} />Back to prioritization</Link><PageHeader eyebrow="Account evidence" title={data?.account || "Account details"} description="Traceable descriptive, prescriptive, predictive, and transaction-level context from the latest successful run." />
    <PageState loading={loading} error={error} onRetry={reload} empty={!loading && !error && !data}><>{data && <>
      <section className="account-hero"><div><span>Current rank</span><strong>#{p?.priority_rank ?? "-"}</strong></div><div><span>Priority Group</span><Badge tone={p?.priority_group || "neutral"}>{p?.priority_group || "Unavailable"}</Badge></div><div><span>Final Priority Score</span><strong>{p?.final_priority_score.toFixed(4) ?? "-"}</strong></div><div><span>Inactivity Risk</span><Badge tone={p?.inactivity_risk?.startsWith("Lower") ? "positive" : "warning"}>{p?.inactivity_risk || "Unavailable"}</Badge></div><div><span>Latest valid transaction</span><strong className="small-value">{p?.latest_valid_transaction || "-"}</strong></div></section>
      <section className="detail-grid"><div className="data-section"><div className="section-heading"><h2><Calculator />RFM profile</h2><span>Descriptive</span></div><dl className="method-facts"><div><dt>Recency</dt><dd>{p?.recency_days} days / score {p?.recency_score}</dd></div><div><dt>Frequency</dt><dd>{p?.frequency} invoices / score {p?.frequency_score}</dd></div><div><dt>Monetary</dt><dd>{Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(p?.monetary || 0)} / score {p?.monetary_score}</dd></div><div><dt>RFM Score</dt><dd>{p?.rfm_score.toFixed(2)}</dd></div><div><dt>Normalized RFM</dt><dd>{p?.normalized_rfm.toFixed(4)}</dd></div></dl></div>
        <div className="data-section"><div className="section-heading"><h2><Clock3 />Historical Settlement Duration</h2><span>Cost criterion</span></div><dl className="method-facts"><div><dt>Average Settlement Days</dt><dd>{p?.settlement_days_avg.toFixed(1)} days</dd></div><div><dt>Eligible invoices</dt><dd>{data.settlement?.settlement_invoice_count ?? 0}</dd></div><div><dt>Normalized criterion</dt><dd>{p?.normalized_settlement.toFixed(4)}</dd></div></dl></div>
        <div className="data-section"><div className="section-heading"><h2><Scale />Prescriptive contribution</h2><span>CRITIC/MCS</span></div><dl className="method-facts"><div><dt>RFM weight</dt><dd>{((data.critic_weights.rfm || 0) * 100).toFixed(2)}%</dd></div><div><dt>Settlement weight</dt><dd>{((data.critic_weights.settlement || 0) * 100).toFixed(2)}%</dd></div><div><dt>RFM contribution</dt><dd>{((p?.normalized_rfm || 0) * (data.critic_weights.rfm || 0)).toFixed(4)}</dd></div><div><dt>Settlement contribution</dt><dd>{((p?.normalized_settlement || 0) * (data.critic_weights.settlement || 0)).toFixed(4)}</dd></div></dl></div>
        <div className="data-section"><div className="section-heading"><h2><Activity />Predictive and stability</h2><span>Supporting context</span></div><dl className="method-facts"><div><dt>CART output</dt><dd>{p?.inactivity_risk || "Unavailable"}</dd></div><div><dt>Model version</dt><dd>{p?.model_version || "Unavailable"}</dd></div><div><dt>Scenario rank range</dt><dd>{data.sensitivity.minimum_rank ?? "-"}-{data.sensitivity.maximum_rank ?? "-"}</dd></div><div><dt>Group movement rate</dt><dd>{((Number(data.sensitivity.group_movement_rate) || 0) * 100).toFixed(1)}%</dd></div></dl><p className="fine-print">Inactivity Risk does not claim permanent churn and does not determine the Final Priority Score.</p></div></section>
      <section className="data-section"><div className="section-heading"><div><span className="eyebrow">Source traceability</span><h2><ReceiptText />Invoice history</h2></div><span>{data.transactions.length} logical invoices</span></div><div className="table-wrap"><table><thead><tr><th>SI No.</th><th>SI Date</th><th>SI Amount</th><th>Final CR Date</th><th>Status</th><th>Reconciled</th><th>Import Batch</th></tr></thead><tbody>{data.transactions.map(row => <tr key={String(row.invoice_group_id)}><td>{String(row.si_no)}</td><td>{String(row.si_date)}</td><td>{Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(Number(row.si_amount))}</td><td>{String(row.final_cr_date || "Unavailable")}</td><td>{String(row.payment_status)}</td><td>{row.reconciled ? "Yes" : "No"}</td><td className="mono">{String(row.import_batch_id).slice(0, 8)}</td></tr>)}</tbody></table></div></section>
    </>}</></PageState></div>;
}
