"use client";

import { Activity, CalendarDays, CircleDollarSign, Clock, Database, Scale, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, PageState } from "@/components/page-state";
import { useApi } from "@/lib/use-api";
import type { DashboardData } from "@/types/dss";

const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", notation: "compact", maximumFractionDigits: 1 });
const colors = { High: "#147d64", Medium: "#d28b24", Low: "#7a8792" };

export default function DashboardPage() {
  const { data, error, loading, reload } = useApi<DashboardData>("/dashboard");
  const empty = error.includes("No successful analytical run");
  const groups = data ? Object.entries(data.priority_group_counts).map(([name, value]) => ({ name, value })) : [];
  return <div className="page-stack"><PageHeader eyebrow="Latest successful run" title="Management overview" description="Current account-prioritization evidence from validated historical sales and collection records." />
    <PageState loading={loading} error={empty ? "" : error} empty={empty} onRetry={reload}><>{data && <>
      <section className="kpi-grid"><div className="kpi-card"><span className="kpi-icon teal"><CalendarDays /></span><div><span>Analysis cutoff</span><strong>{data.run.cutoff_date ?? "Unavailable"}</strong><small>Run {data.run.analysis_run_id.slice(0, 8)}</small></div></div><div className="kpi-card"><span className="kpi-icon blue"><Users /></span><div><span>Standardized accounts</span><strong>{data.total_standardized_accounts}</strong><small>{data.mcs_eligible_accounts} MCS eligible</small></div></div><div className="kpi-card"><span className="kpi-icon amber"><CircleDollarSign /></span><div><span>Valid historical sales</span><strong>{money.format(data.total_valid_historical_sales)}</strong><small>Unique valid invoices</small></div></div><div className="kpi-card"><span className="kpi-icon red"><Activity /></span><div><span>CART model</span><strong className="metric-text">{data.cart_status}</strong><small>Supporting context only</small></div></div></section>
      <section className="dashboard-grid"><div className="chart-section"><div className="section-heading"><div><span className="eyebrow">Decision distribution</span><h2>Priority groups</h2></div><span>{data.mcs_eligible_accounts} ranked accounts</span></div><div className="chart-with-legend"><ResponsiveContainer width="55%" height={250}><PieChart><Pie data={groups} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={2}>{groups.map(item => <Cell key={item.name} fill={colors[item.name as keyof typeof colors]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="chart-legend">{groups.map(item => <div key={item.name}><span style={{ background: colors[item.name as keyof typeof colors] }} /><strong>{item.value}</strong><small>{item.name} Priority</small></div>)}</div></div></div>
        <div className="chart-section"><div className="section-heading"><div><span className="eyebrow">Historical foundation</span><h2>Annual valid SI sales</h2></div><span>Partial year flagged in data</span></div><ResponsiveContainer width="100%" height={250}><BarChart data={data.sales_trend}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="year" /><YAxis tickFormatter={value => Intl.NumberFormat("en", { notation: "compact" }).format(value)} /><Tooltip formatter={value => money.format(Number(value))} /><Bar dataKey="valid_si_sales" fill="#2864a7" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section>
      <section className="dashboard-grid bottom"><div className="data-section"><div className="section-heading"><div><span className="eyebrow">Management attention</span><h2>Top prioritized accounts</h2></div><a href="/accounts">View all accounts</a></div><div className="compact-list">{data.top_accounts.slice(0, 6).map(row => <a href={`/accounts/${encodeURIComponent(row.account)}`} key={row.account}><span className="compact-rank">{row.priority_rank}</span><div><strong>{row.account}</strong><small>{row.priority_group} Priority</small></div><span className="score">{row.final_priority_score.toFixed(4)}</span></a>)}</div></div>
        <div className="data-section"><div className="section-heading"><div><span className="eyebrow">Method transparency</span><h2>Run configuration</h2></div><Scale /></div><dl className="method-facts"><div><dt>CRITIC RFM weight</dt><dd>{((data.critic_weights.rfm ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>CRITIC Settlement weight</dt><dd>{((data.critic_weights.settlement ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>Higher inactivity risk</dt><dd>{data.risk_counts["Higher Inactivity Risk"] ?? 0}</dd></div><div><dt>Lower inactivity risk</dt><dd>{data.risk_counts["Lower Inactivity Risk"] ?? 0}</dd></div><div><dt>Generation time</dt><dd>{data.run.duration_seconds?.toFixed(2) ?? "-"} sec</dd></div><div><dt>Publication status</dt><dd className="success-text">Successful</dd></div></dl></div></section>
    </>}</></PageState></div>;
}
