"use client";

import { Activity, CalendarDays, CircleDollarSign, Scale, Users } from "lucide-react";
import Link from "next/link";
import { PageHeader, PageState } from "@/components/page-state";
import { useApi } from "@/lib/use-api";
import type { DashboardData } from "@/types/dss";

const money = new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP", notation: "compact", maximumFractionDigits: 1 });

export default function DashboardPage() {
  const { data, error, loading, reload } = useApi<DashboardData>("/dashboard");
  const empty = error.includes("No successful analytical run");
  const groups = data ? Object.entries(data.priority_group_counts).map(([name, value]) => ({ name, value })) : [];
  return <div className="page-stack"><PageHeader eyebrow="Latest successful run" title="Management overview" description="Current account-prioritization evidence from validated historical sales and collection records." />
    <PageState loading={loading} error={empty ? "" : error} empty={empty} onRetry={reload}><>{data && <>
      <section className="kpi-grid"><div className="kpi-card"><span className="kpi-icon teal"><CalendarDays /></span><div><span>Analysis cutoff</span><strong>{data.run.cutoff_date ?? "Unavailable"}</strong><small>Run {data.run.analysis_run_id.slice(0, 8)}</small></div></div><div className="kpi-card"><span className="kpi-icon blue"><Users /></span><div><span>Current account profiles</span><strong>{data.total_standardized_accounts}</strong><small>{data.mcs_eligible_accounts} MCS eligible</small></div></div><div className="kpi-card"><span className="kpi-icon amber"><CircleDollarSign /></span><div><span>Valid historical sales</span><strong>{money.format(data.total_valid_historical_sales)}</strong><small>Unique valid invoices</small></div></div><div className="kpi-card"><span className="kpi-icon red"><Activity /></span><div><span>CART model</span><strong className="metric-text">{data.cart_status}</strong><small>Supporting context only</small></div></div></section>
      <section className="dashboard-grid"><div className="data-section"><div className="section-heading"><div><span className="eyebrow">Decision distribution</span><h2>Priority groups</h2></div><span>{data.mcs_eligible_accounts} ranked accounts</span></div><div className="compact-list">{groups.map(item => <Link href={"/accounts?priority_group=" + item.name} key={item.name}><div><strong>{item.name} Priority</strong><small>Recommended attention tier</small></div><span className="score">{item.value}</span></Link>)}</div></div>
        <div className="data-section"><div className="section-heading"><div><span className="eyebrow">Historical foundation</span><h2>Annual valid SI sales</h2></div><span>Detailed visuals in Power BI</span></div><div className="table-wrap"><table><thead><tr><th>Year</th><th>Valid SI sales</th></tr></thead><tbody>{data.sales_trend.map((row, index) => <tr key={String(row.year ?? index)}><td><strong>{String(row.year ?? "-")}</strong></td><td>{money.format(Number(row.valid_si_sales ?? 0))}</td></tr>)}</tbody></table></div></div></section>
      <section className="dashboard-grid bottom"><div className="data-section"><div className="section-heading"><div><span className="eyebrow">Management attention</span><h2>Top prioritized accounts</h2></div><Link href="/accounts">View all accounts</Link></div><div className="compact-list">{data.top_accounts.slice(0, 6).map(row => <Link href={`/accounts/${encodeURIComponent(row.account)}`} key={row.account}><span className="compact-rank">{row.priority_rank}</span><div><strong>{row.account}</strong><small>{row.priority_group} Priority</small></div><span className="score">{row.final_priority_score.toFixed(4)}</span></Link>)}</div></div>
        <div className="data-section"><div className="section-heading"><div><span className="eyebrow">Method transparency</span><h2>Run configuration</h2></div><Scale /></div><dl className="method-facts"><div><dt>CRITIC Recency weight</dt><dd>{((data.critic_weights.recency ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>CRITIC Frequency weight</dt><dd>{((data.critic_weights.frequency ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>CRITIC Monetary weight</dt><dd>{((data.critic_weights.monetary ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>CRITIC Settlement weight</dt><dd>{((data.critic_weights.settlement ?? 0) * 100).toFixed(2)}%</dd></div><div><dt>Higher predicted inactivity risk</dt><dd>{data.risk_counts.Higher ?? 0}</dd></div><div><dt>Lower predicted inactivity risk</dt><dd>{data.risk_counts.Lower ?? 0}</dd></div><div><dt>CART horizon</dt><dd>{data.cart_horizon?`${data.cart_horizon} months`:"Unavailable"}</dd></div><div><dt>Analytics run duration</dt><dd>{data.run.duration_seconds?.toFixed(2) ?? "-"} sec</dd></div><div><dt>Publication status</dt><dd className="success-text">Successful</dd></div></dl><Link className="button secondary" href="/reports">Open detailed reporting</Link></div></section>
      {data.sensitivity.length>0&&<section className="data-section"><div className="section-heading"><div><span className="eyebrow">Decision stability</span><h2>Sensitivity summary</h2></div><span>Published run evidence</span></div><div className="table-wrap"><table><thead><tr><th>Weight perturbation</th><th>Mean Spearman</th><th>Mean group movement</th><th>Maximum group movement</th></tr></thead><tbody>{data.sensitivity.map(row=><tr key={String(row.weight_range)}><td>+/- {(Number(row.weight_range)*100).toFixed(0)}%</td><td>{Number(row.mean_spearman).toFixed(4)}</td><td>{(Number(row.group_movement_rate)*100).toFixed(2)}%</td><td>{(Number(row.max_group_movement_rate)*100).toFixed(2)}%</td></tr>)}</tbody></table></div></section>}      {data.warnings.length>0&&<section className="method-note"><Activity/><div><strong>Run attention items</strong><span>{data.warnings.join(" ")}</span></div></section>}
    </>}</></PageState></div>;
}
