"use client";
import { Activity, GitBranch, Info, ShieldCheck } from "lucide-react";
import { Badge, PageHeader, PageState } from "@/components/page-state";
import { useApi } from "@/lib/use-api";
type Evidence={feature:string;status:string;reason:string;missing_rate:number;gini_importance:number;permutation_importance:number};
type Cart={status:string;outcome_window_months:number;lookback_months:number;model_version:string;development_periods:string[];oop_period:string;majority_baseline:number;confusion_matrix:number[][];feature_evidence:Evidence[];report:{accuracy:number;macro_f1:number};tree_depth:number;leaf_count:number};
export default function CartPage(){
 const {data,error,loading,reload}=useApi<Cart>("/analytics/cart");
 return <div className="page-stack">
  <PageHeader eyebrow="Predictive analytics" title="CART inactivity risk" description="Chronological binary classification using only historical information available at each observation cutoff."/>
  <div className="method-note"><Info/><div><strong>CART provides supporting predictive context.</strong><span>It does not determine the Final Priority Score and does not claim permanent churn.</span></div></div>
  <PageState loading={loading} error={error} onRetry={reload} empty={!data}>
   {data&&<><section className="model-status"><div><span className="model-icon"><Activity/></span><div><span>Model status</span><strong>{data.status}</strong><small>{data.model_version}</small></div></div><Badge tone={data.status==="Validated"?"positive":"warning"}>{data.status}</Badge></section>
   {data.status==="Validated"?<><section className="kpi-grid compact"><div className="kpi-card"><div><span>Outcome window</span><strong>{data.outcome_window_months} months</strong><small>Selected on development data</small></div></div><div className="kpi-card"><div><span>Historical lookback</span><strong>{data.lookback_months} months</strong><small>Versioned configuration</small></div></div><div className="kpi-card"><div><span>OOP macro F1</span><strong>{data.report.macro_f1.toFixed(3)}</strong><small>Untouched final period</small></div></div><div className="kpi-card"><div><span>Majority baseline</span><strong>{(data.majority_baseline*100).toFixed(1)}%</strong><small>Comparison baseline</small></div></div></section>
    <section className="detail-grid"><div className="data-section"><div className="section-heading"><h2><GitBranch/>Temporal validation</h2></div><dl className="method-facts"><div><dt>Development periods</dt><dd>{data.development_periods.length}</dd></div><div><dt>Final OOP cutoff</dt><dd>{data.oop_period}</dd></div><div><dt>Accuracy</dt><dd>{(data.report.accuracy*100).toFixed(1)}%</dd></div><div><dt>Tree depth / leaves</dt><dd>{data.tree_depth} / {data.leaf_count}</dd></div></dl></div>
    <div className="data-section"><div className="section-heading"><h2><ShieldCheck/>Confusion matrix</h2><span>Rows actual, columns predicted</span></div><div className="confusion-grid"><span/><strong>Lower</strong><strong>Higher</strong><strong>Lower</strong><b>{data.confusion_matrix[0]?.[0]??0}</b><b>{data.confusion_matrix[0]?.[1]??0}</b><strong>Higher</strong><b>{data.confusion_matrix[1]?.[0]??0}</b><b>{data.confusion_matrix[1]?.[1]??0}</b></div></div></section>
    <section className="data-section"><div className="section-heading"><div><span className="eyebrow">Multi-basis selection</span><h2>Retained predictive attributes</h2></div><span>Development data only</span></div><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Decision</th><th>Missingness</th><th>Gini importance</th><th>Permutation importance</th><th>Trade-off rationale</th></tr></thead><tbody>{data.feature_evidence.map(row=><tr key={row.feature}><td className="mono">{row.feature}</td><td><Badge tone={row.status==="retained"?"positive":"neutral"}>{row.status}</Badge></td><td>{(row.missing_rate*100).toFixed(1)}%</td><td>{row.gini_importance.toFixed(4)}</td><td>{row.permutation_importance.toFixed(4)}</td><td className="wrap-cell">{row.reason}</td></tr>)}</tbody></table></div></section></>:<div className="state-inline warning-state"><Activity/><div><strong>Predictive context is unavailable for this run.</strong><span>Descriptive and prescriptive DSS functions continue without fabricated risk classifications.</span></div></div>}</>}
  </PageState>
 </div>;
}
